export const merchantBrand = {
  name: "CAVA",
  shortName: "CAVA",
  tagline: "Mediterranean bowls, pitas, and plates.",
  merchantId: "2651",
  surveySlug: "cava",
  surveyUrl: "https://tattleapp.com/cava",
  surveyShortUrl: "tattl.app/cava48291",
  banner: "/CAVA profile banner.jpg",
  logo: "/CAVA logo.jpg",
  primaryColor: "#1a1a1a",
  accentColor: "#e8823c",
  rcsAccent: "#4ba64e",
  teamSignature: "CAVA Team",
  emailFrom: "CAVA <feedback@cava.com>",
  emailSubject: "We want to hear from you!",
};
